### ISSUE TITLE
Eclipse Neon

### ISSUE THREAD

**Issue by Nukium** [christhomas/esftp#1]
This plugin seems to not be detected anymore by Eclipse neon release while Mars still got it.

**Comment by christhomas** [comment]
Hi Nukium, 

why did you close this ticket? is it because it's working now and it was a user mistake, or for some other reason, can you give me any feedback about this?

**Comment by Nukium** [comment]
Yes sorry, my Eclipse bundle was corrupted and the plugin wasn't detected anymore.

Working fine on the lastest PHP Neon release. 

This still an awesome plugin compared to other solution of "Save & Upload".

**Comment by christhomas** [comment]
thanks, although I'd like to revisit the code and update it, I'm really overworked, so I doubt it'll happen.

lots of things in that plugin that I'm not particularly proud of, nothing serious or dangerous, just well, probably there are better ways to do it :)

thanks for the compliments!
